# Import libraries
library(rvest)
library(dplyr)
library(textstem)
library(tidytext)
library(topicmodels)
library(textmineR)
library(digest)
library(ldatuning)
library(ggplot2)
library(furrr)
library(RColorBrewer)
library(stringr)
library(lubridate)
library(ggplot2)